version: '3.8'

services:
  inventory-service:
    build: 
      context: ./backend
      # 🟢 Tells Docker to use your specific Go Dockerfile
      dockerfile: Dockerfile.inventory 
    env_file:
      - ./backend/.env
    ports:
      - "8081:8080" 

  backend:
    build: 
      context: ./backend
      # 🟢 Tells Docker to use your standard Node.js Dockerfile
      dockerfile: Dockerfile 
    env_file:
      - ./backend/.env
    ports:
      - "8080:4000" 
    environment:
      - INVENTORY_SERVICE_URL=http://inventory-service:8080
    depends_on:
      - inventory-service